---
- name: Create Debian 13 Proxmox VM with Cloud-Init, Docker, Dockge
  hosts: localhost
  gather_facts: no
  
  vars_prompt:
    - name: "pve_api_host"
      prompt: "Enter your Proxmox API host"
      private: no
    - name: "pve_api_user"
      prompt: "Enter your Proxmox API user"
      private: no
    - name: "pve_api_password"
      prompt: "Enter your Proxmox API password"
      private: yes
    - name: "vmid"
      prompt: "Enter the VMID to use"
      private: no
    - name: "username"
      prompt: "VM username"
      private: no
    - name: "password"
      prompt: "VM user password"
      private: no

  
  vars:
    # Provide these as extra vars or edit directly
    pve_api_host: "pve.example.com"
    pve_api_user: "root@pam"
    pve_api_password: "changeme"
    node: "carondelet"
    storage: "local-lvm"
    iso_storage: "local"
    debian_iso_name: "debian-13.0.0-amd64-netinst.iso"
    debian_iso_url: "https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-genericcloud-amd64.qcow2"
    vmid: "120"                 # <-- set this per deployment!
    vm_name: "debian13-cloud-{{ vmid }}"
    username: "myuser"
    password: "mypassword"
    vm_ipv4: "192.168.50.{{ vmid }}"
    vm_gw: "192.168.50.1"
    vm_ram: 2048
    vm_cores: 2
    vm_disk: 12

  tasks:
    - name: Check for Debian 13 ISO on Proxmox host
      ansible.builtin.stat:
        path: "/var/lib/vz/template/iso/{{ debian_iso_name }}"
      delegate_to: "{{ pve_api_host }}"
      register: iso_file
    
    - name: Download latest Debian 13 ISO if missing
      ansible.builtin.get_url:
        url: "{{ debian_iso_url }}"
        dest: "/var/lib/vz/template/iso/{{ debian_iso_name }}"
        mode: '0644'
      delegate_to: "{{ pve_api_host }}"
      when: not iso_file.stat.exists

    - name: Create Debian cloud VM (cloud-init compatible)
      community.general.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        name: "{{ vm_name }}"
        cores: "{{ vm_cores }}"
        memory: "{{ vm_ram }}"
        scsihw: virtio-scsi-pci
        scsi0: "{{ storage }}:12"
        ide2: "{{ storage }}:cloudinit"
        net0: "virtio,bridge=vmbr0"
        ciuser: "{{ username }}"
        cipassword: "{{ password }}"
        ipconfig0: "ip={{ vm_ipv4 }}/24,gw={{ vm_gw }}"
        ostype: l26
        state: present


    - name: Start the VM
      community.general.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        state: started

    - name: Wait for SSH
      ansible.builtin.wait_for:
        host: "{{ vm_ipv4 }}"
        port: 22
        timeout: 240

    - name: Run apt update & upgrade
      ansible.builtin.shell: |
        sudo apt update && sudo apt upgrade -y
      args:
        executable: /bin/bash
      become: yes
      become_user: "{{ username }}"
      delegate_to: "{{ vm_ipv4 }}"

    - name: Install Docker
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com | sh
      args:
        executable: /bin/bash
      become: yes
      become_user: "{{ username }}"
      delegate_to: "{{ vm_ipv4 }}"

    - name: Install Dockge
      ansible.builtin.git:
        repo: 'https://github.com/louislam/dockge.git'
        dest: '/opt/dockge'
      become: yes
      become_user: "{{ username }}"
      delegate_to: "{{ vm_ipv4 }}"
