---
- name: Clone Debian 12 Proxmox VM from Template, Set Cloud-Init, Install Docker & Dockge
  hosts: localhost
  gather_facts: no

  vars_prompt:
    - name: "pve_api_host"
      prompt: "Enter your Proxmox API host"
      private: no
    - name: "pve_api_user"
      prompt: "Enter your Proxmox API user"
      private: no
    - name: "pve_api_password"
      prompt: "Enter your Proxmox API password"
      private: yes
    - name: "vmid"
      prompt: "Enter the VMID to use"
      private: no
    - name: "username"
      prompt: "VM username"
      private: no
    - name: "password"
      prompt: "VM user password"
      private: no

  vars:
    node: "carondelet"
    storage: "local-lvm"
    template_vmid: 198
    vm_name: "debian12-cloud-{{ vmid }}"
    vm_ram: 2048
    vm_cores: 2
    vm_disk: 12
    vm_ipv4: "192.168.50.{{ vmid }}/24"
    vm_gw: "192.168.50.1"

  tasks:
    - name: Clone Debian 12 template and set cloud-init params
      community.general.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        clone: "{{ template_vmid }}"
        name: "{{ vm_name }}"
        full: true
        memory: "{{ vm_ram }}"
        cores: "{{ vm_cores }}"
        ciuser: "{{ username }}"
        cipassword: "{{ password }}"
        ipconfig:
          "0":
            ip: "{{ vm_ipv4 }}"
            gw: "{{ vm_gw }}"
        state: present

    - name: Start the VM
      community.general.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "{{ pve_api_user }}"
        api_password: "{{ pve_api_password }}"
        node: "{{ node }}"
        vmid: "{{ vmid }}"
        state: started

    - name: Wait for SSH to be up
      ansible.builtin.wait_for:
        host: "192.168.50.{{ vmid }}"
        port: 22
        timeout: 240

    - name: Run apt update & upgrade
      ansible.builtin.shell: |
        sudo apt update && sudo apt upgrade -y
      args:
        executable: /bin/bash
      become: yes
      become_user: "{{ username }}"
      delegate_to: "192.168.50.{{ vmid }}"

    - name: Install Docker
      ansible.builtin.shell: |
        curl -fsSL https://get.docker.com | sh
      args:
        executable: /bin/bash
      become: yes
      become_user: "{{ username }}"
      delegate_to: "192.168.50.{{ vmid }}"

    - name: Install Dockge
      ansible.builtin.git:
        repo: 'https://github.com/louislam/dockge.git'
        dest: '/opt/dockge'
      become: yes
      become_user: "{{ username }}"
      delegate_to: "192.168.50.{{ vmid }}"
