---
- name: Create Panopticon Proxmox VM
  hosts: localhost
  collections:
    - community.proxmox
  vars:
    api_host: "{{ PROXMOX_API_HOST }}"
    api_token_id: "{{ PROXMOX_API_TOKEN_ID }}"
    api_token_secret: "{{ PROXMOX_API_TOKEN_SECRET }}"
    vmid: "{{ VMID | default('100') }}"
    node: "pve-node1"
    hostname: "panopticon"
    cpu_cores: "{{ CORES | default('4') }}"
    memory: "{{ MEMORY | default('8192') }}"
    disk: "{{ DISK | default('100') }}"
    net_ip: "{{ IP4 | default('192.168.50.100/24') }}"
    net_gw: "{{ GW | default('192.168.50.1') }}"

  tasks:
    - name: Create VM with custom specs
      community.proxmox.proxmox:
        api_host: "{{ api_host }}"
        api_token_id: "{{ api_token_id }}"
        api_token_secret: "{{ api_token_secret }}"
        node: "{{ node }}"
        hostname: "{{ hostname }}"
        memory: "{{ memory }}"
        cpu: "{{ cpu_cores }}"
        vmid: "{{ vmid }}"
        disk: "{{ disk }}"
        cores: "{{ cpu_cores }}"
        netif: '{"net0":"name=eth0,bridge=vmbr0,ip={{ net_ip }},gw={{ net_gw }},ip6=off"}'
        ostemplate: "local:vztmpl/debian-12-standard_12.1-1_amd64.tar.zst"
        state: present
